{{- if .Values.extraConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.extraConfigMap.name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- with .Values.extraConfigMap.data }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}