{{- if .Values.ConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pre-install-configmap
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
  labels:
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.ConfigMap }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}