{{- if .Values.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  {{- range .Values.secretMounts }}
  name: {{ .secretName }}
  {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
data:
  {{- range $key, $value := .Values.Secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}   