{{- if .Values.secretsProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretsProvider.name }}
spec:
  provider: {{ .Values.secretsProvider.provider }}
  parameters:
    region: {{ .Values.secretsProvider.region }}
    objects: |
      - objectName: {{ .Values.secretsProvider.name }}
        objectType: "secretsmanager"
        jmesPath:
            {{- if .Values.secretsProvider.objects }}
            {{ toYaml .Values.secretsProvider.objects | nindent 10 }}
            {{- end }}

  secretObjects:
  - secretName: {{ .Values.secretsProvider.name }}
    type: Opaque
    data:
    {{- if .Values.secretsProvider.data }}
    {{ toYaml .Values.secretsProvider.data | nindent 10 }}
    {{- end }}
{{- end -}}       
    