{{- if .Values.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  {{- range .Values.secretMounts }}
  name: {{ .secretName }}
  {{- end }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
data:
  {{- range $key, $value := .Values.Secrets.data }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}   