{{- if .Values.extraSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.extraSecrets.name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
data:
  {{- range $key, $value := .Values.extraSecrets.data }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}   