apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ include "tpl.servicename" . }}
  labels:
{{- include "tpl.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}    
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}  
spec:
  type: {{ .Values.service.type }}
  ports:
{{- if .Values.service.servicePorts }}
{{ toYaml .Values.service.servicePorts | indent 2 }}
{{- end }}
  selector:
    {{- include "tpl.selectorLabels" . | nindent 4 }}
